### PR TITLE
Add support for accessing linked accounts, transaction pagination, PDF note parser.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Also:
1. Fix an exception when an account has no holdings
2. Remove the Console.ReadLine() from example. Whoever is able to run the example was able to compile it, which was already  done in either a terminal, or in an IDE, at which point there is no point to wait for input. Makes the Modify -> Run -> Modify run development loop annoying as you always have to provide the input.

### CODE REVIEW

**Review by danieldearlove — APPROVED** [review]
I also noticed that this library did not support multiple transaction pages. You got there first.

**Comment by AudriusButkevicius** [comment]
I also have a branch that adds a prometheus exporter sample application, for tracking portfolio stats longer term:
https://github.com/AudriusButkevicius/hl-api-client-net/commits/prom-exporter

**Review by jonathanmadeley — APPROVED** [review]
Great additions @AudriusButkevicius, I haven't had a lot of time lately but was trying to find the time to add Contract Notes, but you beat me to it :raised_hands:

**Review by alandoherty — APPROVED** [review]
LGTM!

**Comment by AudriusButkevicius** [comment]
Sadly I can't merge myself

**Pull request merged**
